version: '3.4'
services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  app2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3000